### ISSUE TITLE
Error Json format Parsing

### ISSUE THREAD

**Issue by ArnaudT** [SumoLogic/elasticsearch-client#65]
Hi,

The error json message mapping from elasticsearch seems incorrect.

We have the following stacktrace when a document is missing:

```
org.json4s.package$MappingException: No usable value for error
Do not know how to convert JObject(List((root_cause,JArray(List(JObject(List((type,JString(document_missing_exception)), (reason,JString([engine_product][37035513]: document missing)), (shard,JString(1)), (index,JString(product))))))), (type,JString(document_missing_exception)), (reason,JString([engine_product][37035513]: document missing)), (shard,JString(1)), (index,JString(product)))) into class java.lang.String
  at org.json4s.reflect.package$.fail(package.scala:93)
  at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$buildCtorArg(Extraction.scala:509)
  at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:529)
  at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$14.apply(Extraction.scala:529)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
```

for the following error message:

```
{
    "error": {
        "root_cause": [{
            "type": "document_missing_exception",
            "reason": "[engine_product][37035513]: document missing",
            "shard": "1",
            "index": "product"
        }],
        "type": "document_missing_exception",
        "reason": "[engine_product][37035513]: document missing",
        "shard": "1",
        "index": "product"
    },
    "status": 404
}
```

The class `ElasticErrorResponse`  can not be mapped by json4s because the error is not a String but an Object.

```
case class ElasticErrorResponse(error: String, status: Int) extends Exception(s"ElasticsearchError(status=$status): $error")
```

We can reproduce the error with the following test:

```
package com.sumologic.elasticsearch.restlastic

import com.sumologic.elasticsearch.restlastic.RestlasticSearchClient.ReturnTypes.ElasticErrorResponse
import org.json4s._
import org.json4s.native.JsonMethods._
import org.scalatest.{Matchers, WordSpec}

class ElasticErrorResponseTest extends WordSpec with Matchers {
  private implicit val formats = org.json4s.DefaultFormats

  "RestlasticSearchClient" should {
    "Be able to create an index and setup index setting with keyword lowercase analyzer" in {
      val jsonTree = parse(errorDocumentMissing)
      val errorMessage = jsonTree.extract[ElasticErrorResponse]
      errorMessage should be(ElasticErrorResponse("document_missing_exception", 404))
    }
  }
  val errorDocumentMissing = """{"error":{"root_cause":[{"type":"document_missing_exception","reason":"[engine_product][37035513]: document missing","shard":"1","index":"product"}],"type":"document_missing_exception","reason":"[engine_product][37035513]: document missing","shard":"1","index":"product"},"status":404} """
}
```

We can have also the following error from ES:

```
{"message":"The security token included in the request is expired"} 
```

So I suppose the error json format change regarding the http status code.

Arnaud.

**Comment by rcoh** [comment]
I'll see if I can convert the error to a JValue instead..

**Comment by CCheSumo** [comment]
https://github.com/SumoLogic/elasticsearch-client/pull/125

**Comment by CCheSumo** [comment]
This has been fixed https://github.com/SumoLogic/elasticsearch-client/pull/125
